### ISSUE TITLE
Is it possible to integrate crab-llvm at the library level?

### ISSUE THREAD

**Issue by ghost** [seahorn/clam#14]
Hi,

I play around with your `crab-llvm` tool and see that it can generate many interesting invariants, such as the Apron's polka or the reduced product of intervals and congruences domain. 

I would like to integrate and test it further in my project, which also uses LLVM infrastructure (but version 3.2), could you advise me a starting point so that I can pass the CFG (llvm data structures) in my project to your `crab-llvm` library to compute the invariant of a specific basic block?

Another off-topic question I would like to ask is that `crab-llvm` uses Apache license, whereas the `Apron` library uses LGPL license. Are these two licenses compatible?

Thank you for your time when considering my question!

**Comment by caballa** [comment]
The only solution I can see is to port your project to llvm 3.6.
I ported recently `crab-llvm` from 3.6 to 3.8 and it was relatively easy. 
From 3.2 to 3.6 it will be harder but I think it's something you would like to do anyway. The  3.2 version is really old.

Once your project is in 3.6 you can call `crab-llvm` via LLVM pass manager or without it. 

Regarding the license question I think they are.

**Comment by ghost** [comment]
Thank you for your answer! Porting `llvm` from 3.2 to 3.6 is indeed tricky, but I will try.

**Comment by caballa** [comment]
Sometimes it's better to port in several steps. For instance, you might try from 3.2 to 3.4 first and then from 3.4 to 3.6. To try directly from 3.2 to 3.6 might be too hard.
