### ISSUE TITLE
install clang-3.8

### ISSUE THREAD

**Issue by tregua87** [seahorn/clam#24]
I am experimenting with crab-llvm.

I installed crab llvm by following the guide in the repo, everything worked well.

However, I have some trouble with clang 3.8.

It is not clear whether I should install clang 3.8 from scratch (and also a parallel llvm installation), or else I should refer to the custom clang repo here (https://github.com/seahorn/clang).

Currently, I am working with Ubuntu 18.04 and the oldest clang in apt is 3.9.

May you give me a clue about this issue, please?

**Comment by caballa** [comment]
For Ubuntu 18.04 you would need to install clang from sources (http://releases.llvm.org/download.html)

You can do that or you can try the branch `dev-llvm-5.0` That one requires clang 5.0 which you should be able to install via apt.

**Comment by tregua87** [comment]
Thank caballa.

I wonder whether dev-llvm-5.0 is stable enough. 

I should deal with function pointers.

**Comment by caballa** [comment]
crab-llvm relies of a pointer analysis that is run as a pre-analysis step to resolve indirect calls through function pointers. You will need to enable the option `--devirt`. That part shouldn't differ from the main branch.

**Comment by tregua87** [comment]
Thanks, I managed to compile on dev-llvm-5.0.

**disclaimer:** If the following question is off-topic, I will be happy to open a new issue. Just let me know.

So, my environment now is: 
- Ubuntu 18.04.
- clang-5.0 (from apt).
- crab-llvm on dev-llvm-5.0 branch.

Moreover, I compiled crab by issuing the following commands (by setting a proper value for \_DIR\_):
```
mkdir build && cd build
 cmake -DCMAKE_INSTALL_PREFIX=_DIR_ -DUSE_LDD=ON -DUSE_APRON=ON ../
 cmake --build . --target extra                 
 cmake --build . --target crab && cmake ..
 cmake --build . --target ldd && cmake ..
 cmake --build . --target apron && cmake ..
 cmake --build . --target llvm && cmake ..                
 cmake --build . --target install 
```

I tried to analyze this example, namely `test.c`:
```
int a (void);
int b (void);

int main(int argc, char** argv) {
  int (*p) (void);
  if (argc == 1)
      p = a;
  else
      p = b;
  int x = p();
  return 0;
}

int a() {return 10;}
int b() {return 5;}
```

By running:
`crabllvm.py test.c --devirt-functions --crab-track=ptr  --lower-select`

The output is:
```
function main
_3:
/**
  INVARIANTS: ({}, {})
**/
  goto __@bb_1,__@bb_2;
__@bb_1:
  assume ( = 1);
  goto TrueLowerSelect;
TrueLowerSelect:
/**
  INVARIANTS: ({}, { -> [1, 1]})
**/
  PHILowerSelect = &(a) + 0;
/**
  INVARIANTS: ({}, { -> [1, 1]})
**/
  goto LowerSelect;
LowerSelect:
/**
  INVARIANTS: ({}, {})
**/
  _ret = call seahorn.bounce(PHILowerSelect:ptr);
  @V_7 = 0;
  return @V_7;
/**
  INVARIANTS: ({}, {@V_7 -> [0, 0]})
**/

__@bb_2:
  assume ( != 1);
  goto FalseLowerSelect;
FalseLowerSelect:
/**
  INVARIANTS: ({}, {})
**/
  PHILowerSelect = &(b) + 0;
/**
  INVARIANTS: ({}, {})
**/
  goto LowerSelect;

function a
_ret:
/**
  INVARIANTS: ({}, {})
**/
  @V_9 = 10;
  return @V_9;
/**
  INVARIANTS: ({}, {@V_9 -> [10, 10]})
**/


function b
_ret:
/**
  INVARIANTS: ({}, {})
**/
  @V_10 = 5;
  return @V_10;
/**
  INVARIANTS: ({}, {@V_10 -> [5, 5]})
**/

CRABLLVM WARNING: skipped indirect call. Enable --devirt-functions

function seahorn.bounce
entry:
/**
  INVARIANTS: ({}, {})
**/
  goto __@bb_1,__@bb_2;
__@bb_1:
  assume_ptr(funcPtr == b);
  goto b;
b:
/**
  INVARIANTS: ({}, {})
**/
  _1 = call b();
  UnifiedRetVal = _1;
/**
  INVARIANTS: ({}, {_1-UnifiedRetVal<=0, UnifiedRetVal-_1<=0})
**/
  goto UnifiedReturnBlock;
UnifiedReturnBlock:
/**
  INVARIANTS: ({}, {})
**/
  return UnifiedRetVal;
/**
  INVARIANTS: ({}, {})
**/

__@bb_2:
  assume_ptr(funcPtr != b);
  goto test.a;
test.a:
/**
  INVARIANTS: ({}, {})
**/
  goto __@bb_3,__@bb_4;
__@bb_3:
  assume_ptr(funcPtr == a);
  goto a;
a:
/**
  INVARIANTS: ({}, {})
**/
  _0 = call a();
  UnifiedRetVal = _0;
/**
  INVARIANTS: ({}, {_0-UnifiedRetVal<=0, UnifiedRetVal-_0<=0})
**/
  goto UnifiedReturnBlock;
__@bb_4:
  assume_ptr(funcPtr != a);
  goto default;
default:
/**
  INVARIANTS: ({}, {})
**/
  havoc(_2);
  UnifiedRetVal = _2;
/**
  INVARIANTS: ({}, {_2-UnifiedRetVal<=0, UnifiedRetVal-_2<=0})
**/
  goto UnifiedReturnBlock;
----------------------------------------------------------------------
BRUNCH_STAT Clang 0.02
BRUNCH_STAT CrabLlvm 0.00
BRUNCH_STAT CrabLlvmPP 0.00
----------------------------------------------------------------------
```

My doubt is double:
1. How do I interpret the output?
2. Even if I set `--devirt-functions` I get `CRABLLVM WARNING: skipped indirect call. Enable --devirt-functions` in the output. Why?

More general, is there a kind of guide or documentation for crab?

Thanks in advance.

**Comment by caballa** [comment]
Hi Flavio, 

Please go to issue #25 to follow the discussion about indirect calls.
