### ISSUE TITLE
[llvm-dis] Invalid instruction with no BB

### ISSUE THREAD

**Issue by Liblor** [seahorn/clam#31]
Hello,

I get the following error if I call `llvm-dis` after running crab-llvm on the c code below:
`llvm-dis: error: Invalid instruction with no BB (Producer: 'LLVM5.0.2' Reader: 'LLVM 5.0.2')`

**Information to reproduce the bug:**
Crab-llvm: Docker build (i.e. with apron)

```
$ crabllvm --version
LLVM (http://llvm.org/):
  LLVM version 5.0.2
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: sandybridge
```
example.c:
```C
#include <stdio.h>

unsigned a;
unsigned x;

int main(int argc, char const* argv[])
{
    a = *(unsigned *) argv[1];
    unsigned b = a;
    unsigned c = 1;

    x = 32;
    x ^= a * 3;

    if (b == 0x55787855)
        printf("SUCCESS\n");
    else
        printf("FAILURE\n");

    printf("0x%x", x);
    return 0;
}
```
How to reproduce:
```
$ crabllvm.py example.c --crab-dom=pk --crab-track=arr --crab-add-invariants=all -o test.crab.bc
[omitted]
$ llvm-dis test.crab.bc
llvm-dis: error: Invalid instruction with no BB (Producer: 'LLVM5.0.2' Reader: 'LLVM 5.0.2')
```

The error occurred with the following domains:
* `pk`
* `term-int`
* `term-dis-int`
* `rtz`

Have a nice day :)

**Comment by caballa** [comment]
Thanks for reporting this problem. I've committed a fix for this.
I'll close this issue for now. Let me know if you encounter more problems.
