### ISSUE TITLE
LLVM-8.0 use sea-dsa to resolve indirect calls

### ISSUE THREAD

**Issue by shankarapailoor** [seahorn/clam#33]
Hi,

I was looking at #25 and I noticed you added dsa support to resolve indirect calls. However, dsa has not been ported to 8.0 but sea-dsa has. Would it be possible to use sea-dsa to resolve indirect calls?

**Comment by caballa** [comment]
Unfortunately, sea-dsa does not resolve indirect calls at this point although it's something I want to do soon.
Currently, only llvm-dsa (old poolalloc implementation) resolves indirect calls. However, llvm-dsa has not been ported to  8.0 although it should be pretty easy to do that.

**Comment by shankarapailoor** [comment]
Thanks a lot!
