### ISSUE TITLE
Crab CFG has no exit

### ISSUE THREAD

**Issue by shankarapailoor** [seahorn/clam#35]
Hi!

Thanks for your help on previous issues. I'm on llvm-8.0 branch and I'm getting the error CRAB ERROR: CFG has no exit when running crabllvm on [this](https://drive.google.com/file/d/17X0iN6B6eZJkz5fpFVc0nuctjnGirPem/view?usp=sharing) file.

My specific commands are:

```bash
./crabllvm -crab-inter -crab-heap-analysis=ci-sea-dsa sshd_pp.bc
```

**Comment by caballa** [comment]
I've committed a fix in crab (59b3d5b0ded62f97d0eb0b644692befe7be3c215)  that hopefully fixes this problem and similar ones. 

Note that you need to update crab. You can do the following:

```
cd crab
git pull origin master
cd ..
cd build && make -j && make install
```

**Comment by caballa** [comment]
Unrelated topic: using `--crab-lower-unsigned-icmp`  might improve precision of the analysis.

**Comment by shankarapailoor** [comment]
Awesome thanks! It seems to work.
