### ISSUE TITLE
Seemingly Spurious Bot Invariants Generated

### ISSUE THREAD

**Issue by shankarapailoor** [seahorn/clam#37]
Hi!

I'm seeing a lot of bottom invariants generated when running crab-llvm from the following [file](https://drive.google.com/file/d/17X0iN6B6eZJkz5fpFVc0nuctjnGirPem/view?usp=sharing). This seems unsound as the program can reach a lot of functions on legitimate inputs in particular function ```do_authentication2```. Any assistance would be great!

```
./crabllvm -crab-inter -crab-print-invariants -crab-heap-analysis=llvm-dsa sshd_pp.bc
```

**Comment by caballa** [comment]
full command?

**Comment by shankarapailoor** [comment]
Updated

**Comment by caballa** [comment]
@shankarapailoor: the problem should be fixed. Please update crab and let me know if you still encounter problems.

**Comment by shankarapailoor** [comment]
@caballa seems fixed to me! Thanks!
