### ISSUE TITLE
Specify entry point and auto generate nd values

### ISSUE THREAD

**Issue by zunchenhuang** [seahorn/clam#45]
Dear crab-llvm researchers,

I went through the possible options and the test files in the repo. They all start with the main function. I wonder if there a way to specify entry point and auto generate nd values against a testing function? For example, specify the entry point for **"int get_sign(int test)**" function, and auto generate a **nd value** for **int test**. If there is no way to do in current llvm-crab, my current plan is to write another llvm pass to the read the bc file for the function and read its signature.

Thank you very much.

Best,
Phil

**Comment by caballa** [comment]
By default the analysis is intra-procedural so it should be able to analyze a LLVM module without a main. For external functions, if you declare the function as external `extern int get_sign(...)` the analysis will treat `get_sign` as a function that returns non-deterministically an integer.

**Comment by zunchenhuang** [comment]
@caballa  

> the analysis will treat `get_sign` as a function that returns non-deterministically an integer.

So if I want to test again `get_sign`, I have to call it in some other locations and pass some **nd values** from its signature?

**Comment by caballa** [comment]
Ah, I see what you want to do. 
The easiest way is to write a LLVM pass that creates a main function that calls the function you want to test and create nondeterministic values for that function. It's basically what you suggested. 

We do already that in SeaHorn. Take a look at this pass 
https://github.com/seahorn/seahorn/blob/master/lib/Transforms/Utils/DummyMainFunction.cc

**Comment by zunchenhuang** [comment]
@caballa Thanks a lot! Since I have to do it both for **crab** and **seahorn** for my current project, this is really a time saver.

**Comment by zunchenhuang** [comment]
@caballa After I played for a while in **seahorn**, I still encouter some issues:

Firstly I run the
`/home/phoebus/Tools/seahorn/build/run/bin/sea pf -m64 combined.bc --cex=cex.ll` to generate the counter example, I checked this part and `cex.ll` seems good to me.
Then I ran the followings:
```
llvm-link -o merged.bc combined.bc cex.ll
llvm-dis merged.bc
# /home/phoebus/Tools/seahorn/build/run/bin/seapp -o merge.pp.bc --entry-point=divide_by_zero merged.bc
# llvm-dis merged.pp.bc
/home/phoebus/Tools/seahorn/build/run/bin/seapp -o merged.ext.bc --simplifycfg-sink-common=false --only-strip-extern=true --keep-lib-fn merged.bc 
/home/phoebus/Tools/seahorn/build/run/bin/seapp -o merged.ext.int.bc --simplifycfg-sink-common=false --klee-internalize merged.ext.bc
/home/phoebus/Tools/seahorn/build/run/bin/seapp -o merged.ext.int.wmem.pp.bc --entry-point=divide_by_zero merged.ext.int.bc
/home/phoebus/Tools/seahorn/build/run/bin/seapp -o merged.ext.int.wmem.bc --wrap-mem merged.ext.int.wmem.pp.bc
/home/phoebus/Tools/cfe-3.8.0/cmake-build-debug/bin/clang++ -m64 -o test.exe merged.ext.int.wmem.bc /home/phoebus/Tools/seahorn/build/run/lib/libsea-rt.a
```
Since there is no main, I have to run this third to the last one as this:
`/home/phoebus/Tools/seahorn/build/run/bin/seapp -o merged.ext.int.wmem.pp.bc --entry-point=divide_by_zero merged.ext.int.bc`


```
/tmp/merged-932934.o: In function `get_sign':
merged.ext.int.wmem.bc:(.text+0x3d): undefined reference to `seahorn.fn.enter'
merged.ext.int.wmem.bc:(.text+0x82): undefined reference to `verifier.error'
merged.ext.int.wmem.bc:(.text+0xb1): undefined reference to `verifier.error'
merged.ext.int.wmem.bc:(.text+0xd5): undefined reference to `verifier.error'
/tmp/merged-932934.o: In function `main':
merged.ext.int.wmem.bc:(.text+0xf2): undefined reference to `seahorn.fn.enter'
merged.ext.int.wmem.bc:(.text+0xf7): undefined reference to `verifier.nondet.2'
merged.ext.int.wmem.bc:(.text+0x100): undefined reference to `verifier.nondet.2'
clang-3.8: error: linker command failed with exit code 1 (use -v to see invocation)
```
Am I missing some flags here? Thanks a lot.
