### ISSUE TITLE
Docker Pull not Working

### ISSUE THREAD

**Issue by cs1160701** [seahorn/clam#46]
I was trying to install from docker using the suggested command:
` docker pull seahorn/clam_5.0:latest`
But I keep getting the following error
`Error response from daemon: manifest for seahorn/clam_5.0:latest not found: manifest unknown: manifest unknown`
I am using Docker version 19.03.4, build 9013bf583a on Debian GNU/Linux 9 (stretch)

**Comment by caballa** [comment]
There is no `latest` tag.
If you look at https://cloud.docker.com/u/seahorn/repository/docker/seahorn/clam_5.0
you will see the only tag is `xenial`.

**Comment by cs1160701** [comment]
Thanks.
