### ISSUE TITLE
fatal: Could not find the clam executable

### ISSUE THREAD

**Issue by chenxi-yang** [seahorn/clam#48]
Hi,

I am using Mac OSX catalina and follow the installation instruction.
`
 mkdir build && cd build
 cmake -DCMAKE_INSTALL_PREFIX=_DIR_ -DCRAB_USE_LDD=ON -DCRAB_USE_APRON=ON ../
 cmake --build . --target extra                 
 cmake --build . --target crab && cmake ..
 cmake --build . --target ldd && cmake ..
 cmake --build . --target apron && cmake ..
 cmake --build . --target llvm && cmake ..                
 cmake --build . --target install 
`

Things go smooth except I `brew install svn` before ` cmake --build . --target llvm && cmake ..  `.
I got installation succeed after running the above commands. However, when I run `cmake --build . --target test-simple`

I got 
`
lit: [workspace]/crab-llvm/tests/lit.cfg:66: fatal: Could not find the clam executable
make[3]: *** [tests/CMakeFiles/test-simple] Error 2
make[2]: *** [tests/CMakeFiles/test-simple.dir/all] Error 2
make[1]: *** [tests/CMakeFiles/test-simple.dir/rule] Error 2
make: *** [test-simple] Error 2
`

Thanks!

**Comment by caballa** [comment]
You need to add  `-DCMAKE_INSTALL_PREFIX=_DIR_ `  into the environment variable `PATH`. I mean `_DIR_`

**Comment by caballa** [comment]
Also for running the tests you also need to install the python packages `lit` and `OutputCheck`
(https://github.com/seahorn/crab-llvm#requirements)

**Comment by chenxi-yang** [comment]
I installed python packages, execute the following command and install again
export PATH=$PATH:[workspace]/crab-llvm/build/

but the error still occurs

**Comment by caballa** [comment]
`[workspace]/crab-llvm/build/` is not the right place. This is the build directory.

Did you do `cmake --build . --target install` or `make install` ?
After that, you need to add to `PATH` the directory `_DIR_/bin`

**Comment by chenxi-yang** [comment]
Got! I used `cmake --build . --target install`
I added _DIR_/bin to PATH, and another error occurs, no other log appears this time
`lit: [workspace]/crab-llvm/tests/lit.cfg:74: fatal: Could not find llvm-dis`

**Comment by caballa** [comment]
Same thing, you need to make sure that `llvm-dis` can be found.
