### ISSUE TITLE
/usr/bin/ld: cannot find -lLLVMExtensions

### ISSUE THREAD

**Issue by zunchenhuang** [seahorn/clam#58]
When I tried to build the clam, in the last few steps: it shows the following.
[ 57%] Built target SeaInstCombine
[ 57%] Building CXX object llvm-seahorn/tools/opt/CMakeFiles/seaopt.dir/AnalysisWrappers.cpp.o
[ 59%] Building CXX object llvm-seahorn/tools/opt/CMakeFiles/seaopt.dir/CallGraphPrinterWrapper.cc.o
[ 61%] Building CXX object llvm-seahorn/tools/opt/CMakeFiles/seaopt.dir/GraphPrinters.cpp.o
[ 61%] Building CXX object llvm-seahorn/tools/opt/CMakeFiles/seaopt.dir/BreakpointPrinter.cpp.o
[ 61%] Building CXX object llvm-seahorn/tools/opt/CMakeFiles/seaopt.dir/NewPMDriver.cpp.o
[ 62%] Building CXX object llvm-seahorn/tools/opt/CMakeFiles/seaopt.dir/PassPrinters.cpp.o
[ 62%] Building CXX object llvm-seahorn/tools/opt/CMakeFiles/seaopt.dir/PrintSCC.cpp.o
[ 64%] Building CXX object llvm-seahorn/tools/opt/CMakeFiles/seaopt.dir/opt.cpp.o
[ 64%] Linking CXX executable ../../../bin/seaopt
/usr/bin/ld: cannot find -lLLVMExtensions
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [llvm-seahorn/tools/opt/CMakeFiles/seaopt.dir/build.make:319: bin/seaopt] Error 1
make[1]: *** [CMakeFiles/Makefile2:2383: llvm-seahorn/tools/opt/CMakeFiles/seaopt.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 64%] Linking CXX static library ../../../lib/libSeaDsaAnalysis.a
[ 64%] Built target SeaDsaAnalysis
make: *** [Makefile:152: all] Error 2

Which part of LLVM did I miss?

I used both from the " cmake --build . --target llvm && cmake .. " and also a local version. Both had the same ld error. 

Thank you very much and any suggestions would be much appreciated.

System: ubuntu 20.04

LLVM 10.0.0 is buggy, which should not be used...

**Comment by caballa** [comment]
Probably you are using LLVM 10.0.0 and it's buggy. Instead,  use LLVM 10.0.1.

**Comment by caballa** [comment]
There is also a branch `dev11` that works with LLVM 11 in case it's easy for you.

**Comment by zunchenhuang** [comment]
@caballa Thank you so much for the suggestions! You were right LLVM 10.0.0 is buggy and LLVM 11 works smoothly.
