### ISSUE TITLE
Tag analysis questions

### ISSUE THREAD

**Issue by adrianherrera** [seahorn/clam#59]
Hey there!

I am trying to understand the tag analysis described [here](https://github.com/seahorn/clam/wiki/TagAnalysis). I am hoping to implement a static taint analysis using this, but am a bit confused how to do this using the current `__CRAB_intrinsic_check_does_not_have_tag` assert.

If I want to understand what tags (i.e., taint) can reachable a given location, what is the best way to encode this given I only have the "does not have tag" function?

Thanks so much for all of your help!

**Comment by caballa** [comment]
The tag analysis is quite experimental (i.e., not real users yet)  but I'm happy to help if things need to be changed/modified. 

The analysis is a may analysis so it can only prove tags that are not possible. 
That intrinsics allows to check if a tag is not possible. 

If you use the C++ api then you can ask the analysis for all possible tags for a given instruction:
https://github.com/seahorn/clam/blob/master/include/clam/ClamQueryAPI.hh#L42

**Comment by adrianherrera** [comment]
oh cool, I missed that Clam Query API. Thanks @caballa!

I'll close this issue for now and see how I go.
