### ISSUE TITLE
Fail to build shared library

### ISSUE THREAD

**Issue by adrianherrera** [seahorn/clam#62]
Hey Clam devs!

I am unable to build Clam as a shared library.

Here is my build:

```
cmake .. -DCLAM_BUILD_LIBS_SHARED=On -DCRAB_BUILD_LIBS_SHARED=On
```

Doing so gives me a whole bunch of

```
undefined reference to `crab::domains::dis_interval<ikos::z_number>::bottom()'
```

Curiously, I don't see this error when building a static lib.

**Comment by adrianherrera** [comment]
Urgh figured it out; I am blind :)

See https://github.com/seahorn/crab/pull/47

**Comment by caballa** [comment]
Thanks. I've already merged the crab patch. 
I don't remember well but I'm not sure I was able to generate a shared library for Clam. 
LMK if you still have problems.

**Comment by adrianherrera** [comment]
I seem to have built one, so that's a good start.

I also had to make some minor changes to the seadsa CMake files. I'll make a PR in a sec.
