### ISSUE TITLE
How to reproduce Elina paper results

### ISSUE THREAD

**Issue by caballa** [seahorn/clam#67]
This is from https://github.com/seahorn/clam/issues/66. I prefer to open a new issue to address it.

[dengyuhui14](https://github.com/dengyuhui14) wrote: 

I want to see if it is possible to make some improvement to the polyhedra abstract domain based on the ELINA library and Apron library. But first I need to reproduce the experiment in this [paper.](http://elina.ethz.ch/papers/POPL17-Polyhedra.pdf) This paper uses crab-llvm analyzer, but it seems that I can't find crab-llvm. And I don't quite understand how analyzer and abstract domain work together to give invariants. Could you please give me some advice on how to conduct these experiment?

**Comment by caballa** [comment]
crab-llvm was renamed to clam a couple of years ago.  So crab-llvm = clam

In fact, if you type https://github.com/seahorn/crab-llvm then it will
redirected to Clam (https://github.com/seahorn/clam)

To reproduce the results of that paper it shouldn't be hard in theory
but there are some practical considerations to take into account.

First, Clam has been improved a lot, and probably Elina too,
since 2017. Of course, you could get the versions from 2017 since they
are available in Github but you should move forward and use the latest
versions of both Clam and Elina. IMHO, the results published in 2017
should still hold in 2022.

Second, Clam has a lot of options that can be tuned depending on each
class of programs. So you should know which options are the best to
give you the most precise but yet scalable results (which is often
tricky). You can ask the authors of that paper to know which exact
options they ran. Alternatively, since I think they ran on SV-COMP
programs I just pushed in the Clam repository a new yaml configuration
(https://github.com/seahorn/clam/blob/master/yaml-configurations/clam.svcomp19.yaml)
file that selects a reasonable set of options that are suitable for
analyzing SVCOMP19 programs. These are probably not the exact ones
they ran for the paper but again, I think that they should be close
enough to reproduce main results.

In short, you can use the following command to run Clam on SVCOMP19
programs:
```
clam-yaml -y ./yaml-configurations/clam.svcomp19.yaml --crab-dom=pk PROGRAM.c
```
The SVCOMP19 benchmarks are available from
https://github.com/sosy-lab/sv-benchmarks/releases/tag/svcomp19 Note
that SVCOMP19 has many categories (sets of related benchmarks).  I
don't remember which categories Elina authors included for their
experiments. That should be said in the paper. Personally, I used to analyze:
```
ReachSafety-ControlFlow
ReachSafety-Loops
Systems_DeviceDriversLinux64_ReachSafety
```
Note that SVCOMP19 is already quite old. You could try SVCOMP21 or
SVCOMP22?. For that, the competition changed a bit how specifications
were written so keep in mind that if yo go in that route then you need
to make some changes so that Clam can understand how properties are
written.

**Comment by dengyuhui14** [comment]
Thanks for your answer!

Yes, I should use the latest version of both Clam and Elina. 

And thank you so much for pushing the new yaml configuration! I will give it a try!

Yes, the paper mentioned which categories they used. And thanks for telling me which categories you analyzed.

I might try to analyze SVCOMP 19 first.

Thank you so much for your help!

**Comment by dengyuhui14** [comment]
Hi,

I go to build/bin, but I cannot find an executable named clam-yaml. What should I do?

Thank you so much!

**Comment by caballa** [comment]
It's a python script `clam-yaml.py` and it's located in the install directory (same place than `clam.py`). `build/bin` is not the install directory.

**Comment by dengyuhui14** [comment]
Thank you so much!

**Comment by dengyuhui14** [comment]
Hi,

I got some error while typing this command:
```
alex@alex-Vostro-3681:~/clam/py$ python3 clam-yaml.py -y ./yaml-configurations/clam.svcomp19.yaml --crab-dom=pk cdaudio_simpl1_false-unreach-call_true-valid-memsafety_true-termination.cil.c 
usage: clam-yaml.py [-h] [-y YCONFIG] [--dry-run] [--yforce] ...
clam-yaml.py: error: unrecognized arguments: --crab-dom=pk

```

**Comment by caballa** [comment]
Try `clam-yaml.py -y ./yaml-configurations/clam.svcomp19.yaml  PROG.c --crab-dom=pk`

**Comment by dengyuhui14** [comment]
It works! Thank you so much!

**Comment by dengyuhui14** [comment]
Hi Jorge,

I am interested in how Crab invokes functions in Elina. I am going to rewrite `pk` domain in Elina. And when I register the new `pk` domain in Crab, how Crab knows which function to call in my new domain? Am I supposed to implement the same interface as Elina? Or things will be simpler if I directly modify the Elina files instead of registering a new domain? 

Thank you for all the help!

**Comment by caballa** [comment]
You should look at the wrapper in Crab that calls to Elina https://github.com/seahorn/crab/blob/master/include/crab/domains/elina_domains.hpp. If you are going to write a new abstract domain but still use all the Elina datastructures then you can just write a new abstract domain in Elina.  If you look at the above wrapper, it's the same code for zones, octagons and polyhedra. You just need to tell the Elina manager which domain you want to use.   The same holds for Apron domains.

**Comment by dengyuhui14** [comment]
Thank you so much!!!

**Comment by dengyuhui14** [comment]
Hi Jorge,

I asked the ELINA author for the code they ran. It was `sea pf --crab --crab-dom=opt-pk-elina PROGRAM.c`. And today I should run `python3 clam.py PROGRAM.c --crab-dom=pk` instead of `sea pf`?

Thanks!

**Comment by caballa** [comment]
They were running the tool SeaHorn (https://github.com/seahorn/seahorn). 
The command `sea pf --crab` runs a model checker called Spacer (part of Z3) and clam to prove assertions.
If you want to reproduce exactly what they did then you need to run SeaHorn. The active branch is `dev10`.  Take a look at https://github.com/seahorn/seahorn/issues/440 in case you have problems during installation.

**Comment by dengyuhui14** [comment]
Thanks! 

Is it the case that clam generates all the invariants and then pass them to Spacer to prove assertions? So only clam calls the abstract domains? If I just want to generate the invariants and then measures the time that different domain take, can I only use clam?

**Comment by caballa** [comment]
Yes to all your questions, except that Spacer (SeaHorn's model checker) also generates invariants but it doesn't call clam's abstract domains or Elina

**Comment by dengyuhui14** [comment]
Thanks a lot!

**Comment by dengyuhui14** [comment]
Hi Jorge,

I want to print the elina timer after clam finishes analysis. It seems that the elina author prints the timer [here](https://github.com/eth-sri/ELINA/blob/eaefbbd9b42e0e80c0701b5c20b7906e88fbb954/elina_poly/opt_pk_representation.c#L1279). However clam doesn't call this function now. Where should I put these printing statements? Is there a function that clam always call after finishing analysis?

Thank you for all the help!

**Comment by dengyuhui14** [comment]
Hi Jorge,

I use clam to analyze a benchmark from svcomp2016. It didn't finish analysis. I tried several times but it didn't help.

I put the benchmark, output file and the script in [this repo](https://github.com/dengyuhui14/study.git). 

Could you please help me solve this problem?

Thank you for all the help!

**Comment by caballa** [comment]
I looked at your example. The program seems challenging. It's relatively big and there are nested loops.
The good thing is that the memory domain instantiated with intervals proves the two assertions in 3s on my Mac M1. It takes double on a AMD chip. 

However, I tried next the zones domain (difference constraints) but the analysis already takes too long (around 600s).  If zones takes too long then polyhedra will be much worse. I'll try to see how to speed-up analysis but it might not be straightforward.

Why do you think that polyhedra should terminate in reasonable time for this example?

**Comment by dengyuhui14** [comment]
Thanks for running the example for me!

I think polyhedra should terminate because I ran this example using [virtual machine provided by elina](https://www.sri.inf.ethz.ch/popl18-paper251) and it terminated. Though it took quite a long time, around 2e+12 CPU cycles on the elina side. Result file is [here](https://github.com/dengyuhui14/study/blob/ebeb6ae3bce4e711b9b0ceef895280fe36ba7e4c/results2.c). Time is in the last line.

**Comment by caballa** [comment]
This is the kind of thing that you shouldn't try. You are running 2018 version of SeaHorn and trying to compare with 2022 Clam. 2018 SeaHorn was calling Clam (option --horn-crab) but that Clam was much less precise than the current one. The translation from LLVM IR to Crab IR was much less precise and the Crab domains were less precise (no memory domains at that time). All of this means that the version of Clam in that VM will be often much faster but probably the results will be also much poorer (i.e., more often useless). 

Looking at your logs, the program seems much much easier than the one I analyzed today with Clam. In your log, I can see

```
Join Count: 2693
```

When I ran Clam, I counted also number of joins and the number is 176376!

```
BRUNCH_STAT RegionDomain(ArrayAdaptive(ArraySmashing(Product(Boolean,Intervals)))).count.join 176376
``` 

That gives a good idea that the analyzed programs are very different. 
In particular, I don't see the option `--devirt-functions` in your logs. This option resolves indirect calls. So without that function, SeaHorn analyzes a fewer number of functions than it should be. That could explain things but again it's hard to tell since we are talking about 4 years of development between versions. 

Why do you want to reproduce the POPL'18 results with the current version? You have the VM to reproduce those results. If your goal is to improve Elina, you can run 2022 Clam+Elina as baseline and then run 2022 Clam + your elina.

**Comment by dengyuhui14** [comment]
Thanks for pointing out my problem!

I am not trying to reproduce POPL'18 with the current version. I am so sorry that I forgot to open a new issue to ask how to use clam with elina polyhedra to analyze this example.

Yes, my goal is to improve elina, therefore I used VM to reproduce the elina paper results and figured out the bottleneck. Then I found analyzing this example took a long time.  So I wanted to use this example as my benchmark. I wrote my elina and I want to run my elina using 2022 clam instead of VM. So I analyzed this example using clam and elina as baseline first.

I think I am trying to do the things you suggest: run 2022 Clam + Elina as baseline and then run 2022 Clam + my elina.

**Comment by caballa** [comment]
Then run 2022 Clam + Elina on all benchmarks and select those which are interesting for you. I don't think you need to run the the POPL'18 VM for that.

**Comment by dengyuhui14** [comment]
But I need to know which function of elina is the slowest and clam doesn't allow me to print the timer. I want to know how to do that?

**Comment by caballa** [comment]
It's a bit involved. The right way is to add a new abstract operation in the `abstract_domain_api` (https://github.com/seahorn/crab/blob/master/include/crab/domains/abstract_domain.hpp#L58).

An alternative, probably easier but a bit hacky is:

Look for instance at https://github.com/seahorn/crab/blob/master/include/crab/domains/abstract_domain_specialized_traits.hpp#L302

1. You can define instead 

```
template<typename Domain> class stats_domain_traits {
public:
  static void print_stats(void) {}
};
```

Note that the template has a parameter `Domain` which is the abstract domain. 
By default, any instantiation of this class will do nothing in `print_stats`. 

2. Then in https://github.com/seahorn/crab/blob/master/include/crab/domains/elina_domains.hpp you instantiate that  class with something like this:

```
template <typename Number, typename VariableName, elina_domain_id_t ElinaDom>
class stats_domain_traits<elina_domain<Number, VariableName, ElinaDom>> {
public:
  static void print_stats(void) {
    elina_domain<Number, VariableName, ElinaDom>::print_stats();
  }
};
```

and define `print_stats` as a static method inside `elina_domain`

3. Finally, you can call `stats_domain_traits<....>::print_stats()` after you finish the analysis. E.g. if you don't run the inter-procedural analysis since functions are being inlined then you can call from here 

https://github.com/seahorn/crab/blob/master/include/crab/analysis/fwd_analyzer.hpp#L198

I hope you get the idea. Conceptually it's pretty simple but as I said, it requires a bit of coding.

**Comment by dengyuhui14** [comment]
Thank you so much! I get the idea and will try to code it!

**Comment by dengyuhui14** [comment]
Hi Jorge,

I got some error in the third step. Here is my code:
```
  void run_forward(const basic_block_label_t &entry,
                   const assumption_map_t &assumptions) {
    this->run(entry, m_abs_tr->get_abs_value(), assumptions);
    stats_domain_traits<elina_domain<number_t, variable_t, abs_dom_t>>::print_stats();
  }
```
Here is the error message:
```
/home/bigdataflow/dyh/clam/crab/include/crab/analysis/fwd_analyzer.hpp:199:25: error: use of undeclared identifier 'elina_domain'
    stats_domain_traits<elina_domain<number_t, variable_t, abs_dom_t>>::print_stats();
                        ^
1 error generated.
```
I don't know what to put inside `<>`.

Thanks!

**Comment by caballa** [comment]
`abs_dom_t`

**Comment by dengyuhui14** [comment]
Hi Jorge,

It seems that it doesn't work. It didn't print anything I code in ELINA.

First, I defined the class `stats_domain_traits` in [abstract_domain_specialized_traits.hpp](https://github.com/dengyuhui14/study/blob/2089340e7d526ff5a263ab2536c0af1ce98e5c3b/abstract_domain_specialized_traits.hpp#L307) (I upload the files I modified).

Second, In `elina_domains.hpp`, I instantiate the class `stats_domain_traits` [here](https://github.com/dengyuhui14/study/blob/2089340e7d526ff5a263ab2536c0af1ce98e5c3b/elina_domains.hpp#L2038). Then I add a static method `print_stats()` [here](https://github.com/dengyuhui14/study/blob/2089340e7d526ff5a263ab2536c0af1ce98e5c3b/elina_domains.hpp#L94).

Third, I call `print_stats()` in `fwd_analyzer.hpp` [here](https://github.com/dengyuhui14/study/blob/2089340e7d526ff5a263ab2536c0af1ce98e5c3b/fwd_analyzer.hpp#L199).

Finally, I type `ninja install`. After that, I still use this [script](https://github.com/dengyuhui14/study/blob/main/script.sh) to analyze the benchmarks. But it didn't print anything in the `elina_abstract0_fprint()` method to the `${POLYPATH}/${filename}`.

Thanks!

**Comment by caballa** [comment]
Are you sure that line https://github.com/dengyuhui14/study/blob/2089340e7d526ff5a263ab2536c0af1ce98e5c3b/elina_domains.hpp#L97 is the correct way to print stats with elina? I would expect that you need to pass the manager and even a pointer to an abstract state. 

For instance, I call to `elina_abstract0_fprint` here https://github.com/seahorn/crab/blob/master/include/crab/domains/elina_domains.hpp#L621.

If I'm right, `print_stats` needs to take as parameter an abstract state (types `Domain` and `abs_dom_t`). You can probably pass a `const &`.

**Comment by dengyuhui14** [comment]
Thanks a lot! I call the `elina_abstract0_fprint` in a wrong way. I will try to pass the manager. Since I define `print_stats()`  as a static method, I can't use the `apstate`. I will change the `elina_abstract0_fprint` so that it doesn't need a `apstate`.

**Comment by dengyuhui14** [comment]
It doesn't work. In `elina_domains.hpp`, I call `elina_abstract0_fprint(stdout, get_man(), NULL, NULL);`.

I've changed the code in elina as the following, so that it doesn't require a `elina_abstract0_t`. And I also change the function `ptr` so that it doesn't requires a `elina_abstract0_t`.
```
void elina_abstract0_fprint(FILE* stream, elina_manager_t* man,
			 elina_abstract0_t* a,
			 char** name_of_dim)
{
  
  // if (elina_abstract0_checkman1(ELINA_FUNID_FPRINT,man,a)){
    void (*ptr)(FILE*,elina_manager_t*,void*,char**) = man->funptr[ELINA_FUNID_FPRINT];
    //ptr(stream,man,a->value,name_of_dim);
    ptr(stream, man, NULL, name_of_dim);
  // }
  // else {
    // fprintf(stream,"elina_abstract0_c: elina_abstract0_fprint: INVALID_ARGUMENT\n");
  //}
}
```

**Comment by dengyuhui14** [comment]
Hi Jorge,

I put some `fprintf` statements in `fwd_analyzer.hpp`

```
  void run_forward(const basic_block_label_t &entry,
                   const assumption_map_t &assumptions) {
    this->run(entry, m_abs_tr->get_abs_value(), assumptions);
    fprintf(stdout, "inside run_forward\n");
    domains::stats_domain_traits<abs_dom_t>::print_stats();
  }

```

and in `elina_domains.hpp` where I instantiate the class
```
template<typename Number, typename VariableName, elina_domain_id_t ElinaDom>
class stats_domain_traits<elina_domain<Number, VariableName, ElinaDom>> {
public:
  static void print_stats(void) {
    fprintf(stdout, "inside stats_domain_traits::print_stats\n");
    elina_domain<Number, VariableName, ElinaDom>::print_stats();
  }
```
and in class `elina_domain`:
```
 static void print_stats(){
    /*void elina_abstract0_fprint(FILE* stream,
			 elina_manager_t* man, elina_abstract0_t* a, char** name_of_dim);*/
       fprintf(stdout, "inside elina_domain::print_stats\n");
       elina_abstract0_fprint(stdout, get_man(), NULL, NULL);
  }
```

Only the `fprintf` in the `fwd_analyzer.hpp` prints, the other two `fprintf` have no output. The output is like:

```
@V_5:int32 declare ldv__builtin_expect(@V_6:int32,@V_8:int32)
_ret:
/** INVARIANTS: {} **/
  arg = @V_6;
  arg1 = @V_8;
  @V_5 = arg;
/** INVARIANTS: ({}, {-@V_5+@V_6 = 0; arg-@V_5 = 0; -arg1+@V_8 = 0}) **/


inside run_forward
void declare get_current()
_1:
/** INVARIANTS: {} **/


inside run_forward
```

It seems that it didn't enter the function `stats_domain_traits::print_stats`.

**Comment by caballa** [comment]
I'll close this issue. Feel free to open new issues if you have more questions.
