### ISSUE TITLE
Function @verifier.assume has invalid attributes

### ISSUE THREAD

**Issue by foonathan** [seahorn/clam#68]
When using clam to insert invariants, it declares a function @verifier.assume:

```
; Function Attrs: inaccessiblememonly norecurse nounwind optnone
declare void @verifier.assume(i1) #1
```

However, attempting to disassemble the bitcode to LLVM IR generates an error as the function should also have the noinline attribute:

```
Attribute 'optnone' requires 'noinline'!
void (i1)* @verifier.assume
LLVM ERROR: Broken module found, compilation aborted!
```

I had to patch LLVM to get the .ll file and see what's going on by removing the following line: https://github.com/llvm/llvm-project/blob/97d00b72a2b0a7aca631e1402a647f32c4e8bafb/llvm/lib/IR/Verifier.cpp#L2051-L2052

**Comment by caballa** [comment]
Fix in commit https://github.com/seahorn/clam/commit/6b684473c44c7cd9d5368f853c441791c09d9f35.

@foonathan thanks for reporting it!

**Comment by foonathan** [comment]
Thanks for the quick fix!
