### ISSUE TITLE
Question about clam API compile error

### ISSUE THREAD

**Issue by YunMoZhang** [seahorn/clam#74]
I'm using clam API usage and trying to compile the example API usage program in [wiki](https://github.com/seahorn/clam/wiki/ClamAPIUsage). But I was told that
```
myanalyzer.cpp:11:10: fatal error: seadsa/AllocWrapInfo.hh: No such file or directory
 #include "seadsa/AllocWrapInfo.hh"
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
<builtin>: recipe for target 'myanalyzer.o' failed
make: *** [myanalyzer.o] Error 1
```
I have tried to modify the Makefile as indicated by [clam-tutorial](https://github.com/caballa/clam-tutorial) (Actually I'm not sure whether they are correctly setting. For example, whether "installation directory" means the source code directory or ```bin``` in my computer):
```
# Installation directory for clam
CLAM_INSTALL=/home/clam
# Installation directory for llvm
LLVM_HOME=/home/clam/build/llvm-install
# Installation directory for Boost
BOOST_ROOT=/usr/include/boost
# Installation directory for GMP 
GMP_DIR=/usr/include
```
I have already installed sea-dsa under clam.
Then how to solve this error?
Thank you in advance.

**Comment by caballa** [comment]
`CLAM_INSTALL` is the directory where you installed the binaries and headers from Clam and its dependencies. It seems that your build directory is in `/home/clam/build/`. In that directory, you should have a file `CMakeCache.txt`. Open it and search for the variable `CMAKE_INSTALL_PREFIX`. That's the value for `CLAM_INSTALL`

**Comment by YunMoZhang** [comment]
Thank you for your reply! It works for me.
 But when I ```make``` again, new errors appeared. It seems because I haven't installed Apron or Elina. While I don't need them. Is there a way to avoid such errors?
First, after I modified ```CLAM_INSTALL``` in Makefile, the error is:
```
g++: error: /home/clam/build/_CLAM_INSTALL_DIR_/apron/lib/libpolkaMPQ.a: No such file or directory
```
Then I change the Makefile to the below, since my clam is built without external libraries (apron,elina):
```
## Include this file if Clam was built without external libraries
## (ldd, apron, elina)
include Makefile.config


## Include this file if Clam was built with external libraries (ldd,
## apron, elina).
#include Makefile.external.config
```
But there are new errors. All of them happen in ```elina_domains.hpp```. For example :
```
/home/clam/build/_CLAM_INSTALL_DIR_/lib/libClamAnalysis.a(pk.cc.o): In function `crab::domains::elina_domain<ikos::z_number, crab::var_factory_impl::indexed_varname<llvm::Value const*>, (crab::domains::._232)2, crab::domains::ElinaDefaultParams<ikos::z_number> >::operator&=(crab::domains::elina_domain<ikos::z_number, crab::var_factory_impl::indexed_varname<llvm::Value const*>, (crab::domains::._232)2, crab::domains::ElinaDefaultParams<ikos::z_number> > const&)':
/home/clam/crab/include/crab/domains/elina_domains.hpp:1032: undefined reference to `elina_abstract0_copy'
/home/clam/crab/include/crab/domains/elina_domains.hpp:1036: undefined reference to `elina_abstract0_meet'
/home/clam/crab/include/crab/domains/elina_domains.hpp:118: undefined reference to `opt_pk_manager_alloc'
/home/clam/crab/include/crab/domains/elina_domains.hpp:118: undefined reference to `opt_pk_manager_alloc'
/home/clam/crab/include/crab/domains/elina_domains.hpp:118: undefined reference to `opt_pk_manager_alloc'
/home/clam/crab/include/crab/domains/elina_domains.hpp:118: undefined reference to `opt_pk_manager_alloc'
```
Do I have to install apron? Is there any way to use clam API usage without apron and elina?

**Comment by caballa** [comment]
You shouldn't need to install Apron or Elina.
The change you did to the Makefile is correct.
I tried on a mac and I successfully compiled. 
Not sure how I can reproduce your linking error. 

Are you running on a Linux machine? If yes, I can try tomorrow. 
Btw, note please that I wrote this example long time ago and used Makefile at that time. 
I strongly recommend cmake instead which typically would save you this kind of problems.

**Comment by YunMoZhang** [comment]
Got it. Yes, I use Linux. I'll try cmake. Thank you for your advice.
