### ISSUE TITLE
CMake Error: Clam/py/setup.py.in file missing

### ISSUE THREAD

**Issue by zhenwang332** [seahorn/clam#78]
Hello,
I encountered an issue while compiling the project in branch dev12. I received the following error message:
```
CMake Error: File /home/myProjects/Clam/py/setup.py.in does not exist.
CMake Error at py/CMakeLists.txt:20 (configure_file):
  configure_file Problem configuring file
```
Environment:
I use Ubuntu20.04 and compile by Clang12
my cmake options is 
```
-DLLVM_ROOT=path/to/llvm12
-DCMAKE_INSTALL_PREFIX=/path/to/install
-DCLANG-FORMAT=path/to/clang-format
-DUSE_PY_SETUP=ON
```

**Comment by caballa** [comment]
Do you have a special reason to enable `USE_PY_SETUP`?
 
That option was supposed to use python distutils to install all the python stuff but it's old code.
I'll remove it. 

By the way, the current development branch is `dev14`. All the older versions have been frozen and they won't get more fixes. So please use `dev14`.

**Comment by zhenwang332** [comment]
Thank you for quick response.
No special reason, I just followed the README/usage to learn the use of Clam.
The python stuff is old, that's OK. I have built project successfully without DUSE_PY_SETUP , it works well. I will directly use the executable file to study Clam, and switch to dev14 after that.
