### ISSUE TITLE
questions about LLVM versions

### ISSUE THREAD

**Issue by mine-blog** [seahorn/clam#79]
Hello, everyone! It's my pleasure to use your framework, but I'm new here. I would like to know whether the newest version --"supports LLVM14" also supports LLVM10. If you can hear me, thank you for solving my problem.

**Comment by caballa** [comment]
The newest version requires LLVM 14. It won't compile with an older version.

**Comment by mine-blog** [comment]
Oh, thanks for your response, and I get it!
