### ISSUE TITLE
Error Encountered in Clam with Context-Sensitive Heap Analysis: Mismatch in Input Count

### ISSUE THREAD

**Issue by zhenwang332** [seahorn/clam#85]
Hi:  
I encountered an unexpected error while using Clam, and I don't know whether it is a bug or caused by my improper usage. Here are the details:

Command: `clam.py linear_search.c --crab-check=assert  --crab-inter --crab-heap-analysis=cs-sea-dsa-types --crab-track=sing-mem`  
After running the above command, I got the following error:
```
.:int32 declare linear_search(@V_5:int32,@V_7:int32,@V_8:arr(int),@V_10:arr(int))
num of inputs at callsite=3
num of inputs at function=4,
CLAM ERROR: Mismatch of number of inputs between callsite and function declaration at Clam/lib/Clam/CfgBuilder.cc:5259
```
It occurs only when applying context-sensitive heap analysis, and context-insensitive works well. 
After debugging, I found that there seems to be a mistake with the csanalysis while analyzing the inOutRegions of the function.  
It is not necessary for me to use cs analysis, but I suspect that this might be a bug so report it.

My version is cbfcb561b434708eba8d561fa53d6b54b8ae99bb.
The content of linear_search.c is provided below:
```

extern void abort(void);
extern void __assert_fail(const char *, const char *, unsigned int, const char *) __attribute__ ((__nothrow__ , __leaf__)) __attribute__ ((__noreturn__));
void reach_error() { __assert_fail("0", "linear_sea.ch.c", 3, "reach_error"); }
extern void *calloc(unsigned int num, unsigned int size);

void __VERIFIER_assert(int cond) {
  if (!(cond)) {
  ERROR: {reach_error();abort();}
  }
  return;
}
unsigned int __VERIFIER_nondet_uint();
unsigned int  SIZE;
const unsigned int MAX = 100000;
int linear_search(int *a, int n, int q) {
  unsigned int j=0;
  while (j<n && a[j]!=q) {
    j++;
  }
  if (j<SIZE) return 1;
  else return 0;
}
int main() {
  SIZE=(__VERIFIER_nondet_uint()/8)+1;

  if (SIZE > 1 && SIZE < MAX) {
    int *a = calloc(SIZE,sizeof(int));
    a[SIZE/2]=3;
    __VERIFIER_assert(linear_search(a,SIZE,3));
  }
}


```

**Comment by caballa** [comment]
Thanks for reporting this bug.
It has been fixed in commit c34f99e432cd0eb988b081b92ba0c3cb714331de
