### ISSUE TITLE
Clam missing a warning

### ISSUE THREAD

**Issue by andrea1775** [seahorn/clam#87]
Dear all,

I found that Clam misses the assertion violation in the attached code. I.e. for concrete values "s__info_callback = -2147468276" and "s__in_handshake = -1845985984" the assertion fails. I invoked clam.py with option --crab-check=assert. Clam's output is

************** ANALYSIS RESULTS ****************
1 Number of total safe checks
0 Number of total error checks
0 Number of total warning checks
************** ANALYSIS RESULTS END*************
The results were produced working on commit cbfcb561b434708eba8d561fa53d6b54b8ae99bb. 
[file.zip](https://github.com/seahorn/clam/files/12496064/file.zip)

**Comment by caballa** [comment]
Fixed in commit 7a7880a2a5af5465a1c6c3a2a247e67e9abf2876
