### ISSUE TITLE
Clam unexpectly reporting assertion failures

### ISSUE THREAD

**Issue by andrea1775** [seahorn/clam#89]
Dear all,

I found that Clam emits unexpected assertion failures. Consider the program test.c  [test.zip](https://github.com/seahorn/clam/files/12858897/test.zip): Clam reports the assertion as failing even tough it is unreachable. Interestingly this does not happen anymore once we remove the assumption after the assertion.  
I invoked clam.py with option --crab-check=assert. 
The results were produced working on commit a4420033655e7f285c55803ce53ce9ca1e94b2a6.

**Comment by caballa** [comment]
Fixed in commit [3fde304](https://github.com/seahorn/clam/commit/3fde3046e3a4d10690d1a95d3697ba591b534d69)
