### ISSUE TITLE
Crab giving an inconsistent number of warnings

### ISSUE THREAD

**Issue by andrea1775** [seahorn/clam#91]
Hi,
I recently encountered the following behavior:
If I execute `clam.py  --crab-check=assert --crab-lower-unsigned-icmp true` on the following code I see 1 warning:
```
extern void __CRAB_assume(int cond);
extern int __CRAB_nd(void);
extern void __CRAB_assert(int);
int N;
int main() {
  N = __CRAB_nd();
  __CRAB_assume(N != -2147483648 && N != 2147483647);
  for (int i = 0; i < N; i++) {
    __CRAB_assert(N >= -1);
  }
  return 0;
} 
```
This is unexpected, since the assertion should not fail. Interestingly if I drop the completely irrelevant assumption, I see 0 warnings as expected. I am working on Clam version 3fde3046e3a4d10690d1a95d3697ba591b534d69 .

**Comment by caballa** [comment]
Fixed by commit [3a64ddb](https://github.com/seahorn/clam/commit/3a64ddbc7729aa942eab25c0e2fe7071109a83b8)
