### ISSUE TITLE
Clam missing a warning

### ISSUE THREAD

**Issue by andrea1775** [seahorn/clam#93]
Hi,
I recently encountered the following bug:
If I execute `clam.py  --crab-check=assert --crab-lower-unsigned-icmp true` with the following code I see a warning about the first assertion but not about the second assertion.
```
extern int __VERIFIER_nondet_int();
extern void __CRAB_assert(int);
int main() {
  int S = __VERIFIER_nondet_int();
  __CRAB_assert(S != 2U && S != 1U);
  __CRAB_assert(S > 2); 
  return 0;
}
```
The second assertion is clearly unsafe. I'm working with Clam version 3a64ddbc7729aa942eab25c0e2fe7071109a83b8 .

**Comment by caballa** [comment]
Fixed in commit 942b86cbacac9536b733ae4284fedb49c75e98c1
