### ISSUE TITLE
Clam missing a warning about an unsafe assertion

### ISSUE THREAD

**Issue by andrea1775** [seahorn/clam#94]
Hi,
I recently encountered the following bug:
If I execute `clam.py  --crab-check=assert test.c`  with the following code I see no warning about the assertion:
```
extern void __VERIFIER_assume(int);
extern void __CRAB_assert(int);
extern int __VERIFIER_nondet_int(void);

int main() {
  const int MAX = __VERIFIER_nondet_int();
  __VERIFIER_assume(MAX <= 1);
  for (int i = MAX - 1; i >= 0; i--) {
  }
  __CRAB_assert(MAX <= 0);
}
```
However the assertion is unsafe for MAX = 1. I'm working with Clam version b41adfd16fb6e6c74081113f04597e7c5c73f972

**Comment by caballa** [comment]
Fixed by commit [e32aa83](https://github.com/seahorn/clam/commit/e32aa831d2d634bdceb852cb3f66d7f70931e395)
