### ISSUE TITLE
No support for pk and oct domain analysis of master branch

### ISSUE THREAD

**Issue by ghost** [seahorn/clam#96]
I want to use pk and oct domain analysis, but fail when I change the crab-dom to pk or oct in clam.svcomp.yaml.

 CLAM ERROR: Intra-procedural analysis for pk not found. at /clam-master/lib/Clam/Clam.cc:307

How to deal with this problem?

**Comment by caballa** [comment]
Did you compile clam with option `-DCRAB_USE_APRON=ON` or `-DCRAB_USE_ELINA=ON`?

(see https://github.com/seahorn/clam?tab=readme-ov-file#compilation-and-installation)

**Comment by ghost** [comment]
I'm so sorry. This is my mistake. Thank you very much!
