### ISSUE TITLE
Accessing Datalayout when it changed on ClamQueryCache

### ISSUE THREAD

**Issue by LinerSu** [seahorn/clam#99]
- Description:
SEABMC performs [code transformation](https://github.com/seahorn/seahorn/blob/dev14/lib/seahorn/BvOpSem2.cc#L1531) during VC gen. This will affect variable mapping between the LLVM IR and Crab IR. We need to find one way to adapt the changes.
- Reproduce:
  - Code: [hash_iter_done.bc.zip](https://github.com/seahorn/clam/files/15031105/hash_iter_done.bc.zip)
  - Command:
```
seahorn --horn-bmc --horn-bv2 --log=opsem --lower-gv-init-struct=false --horn-shadow-mem-alloc-is-def --keep-shadows=true --sea-dsa=cs --sea-dsa-type-aware --horn-solve -horn-inter-proc -horn-sem-lvl=mem --horn-step=large hash_iter_done.bc --horn-unify-assumes=false --horn-gsa=false --horn-vcgen-use-ite --horn-vcgen-only-dataflow=false --horn-bmc-coi=false --sea-opsem-allocator=static --horn-explicit-sp0=false --horn-bv2-lambdas --horn-bv2-simplify=true --horn-bv2-extra-widemem --horn-stats=true --horn-bv2-crab-check-is-deref --horn-bmc-crab-dom=zones
```

**Comment by caballa** [comment]
Fixed by commit [d089f8c](https://github.com/seahorn/clam/commit/d089f8c000b317adb88b5ade1f4330766d117b04)
